-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."event_states" AS ENUM('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED');--> statement-breakpoint
CREATE TYPE "public"."event_variants" AS ENUM('USER_REGISTERED');--> statement-breakpoint
CREATE TABLE "outbox" (
	"oid" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "outbox_oid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"processed_at" timestamp with time zone,
	"payload" jsonb NOT NULL,
	"attempts" smallint DEFAULT 0 NOT NULL,
	"event_state" "event_states" DEFAULT 'PENDING' NOT NULL,
	"event_variant" "event_variants" NOT NULL,
	CONSTRAINT "attempts" CHECK (attempts >= 0)
);
--> statement-breakpoint
CREATE INDEX "idx_outbox_created_at" ON "outbox" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idx_outbox_event_state_pending" ON "outbox" USING btree ("event_state" enum_ops) WHERE (event_state = 'PENDING'::event_states);
*/